// Code generated by go generate; DO NOT EDIT.
package program

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Program struct {
	Field0 *string `json:"programname"`

	Field1 *string `json:"programtype"`
}

func (r *Repository) List(limit, offset int) ([]Program, error) {
	rows, err := r.db.Query("SELECT ProgramName, ProgramType FROM Program LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Program
	for rows.Next() {
		var s Program
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Program, error) {
	row := r.db.QueryRow("SELECT ProgramName, ProgramType FROM Program WHERE ProgramName = $1", id)
	var s Program
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM Program WHERE ProgramName = $1", id)
	return err
}
