// Code generated by go generate; DO NOT EDIT.
package assessment

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Assessment struct {
	Field0 *string `json:"assessmentidentifier"`

	Field1 *string `json:"assessmenttitle"`
}

func (r *Repository) List(limit, offset int) ([]Assessment, error) {
	rows, err := r.db.Query("SELECT AssessmentIdentifier, AssessmentTitle FROM Assessment LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Assessment
	for rows.Next() {
		var s Assessment
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Assessment, error) {
	row := r.db.QueryRow("SELECT AssessmentIdentifier, AssessmentTitle FROM Assessment WHERE AssessmentIdentifier = $1", id)
	var s Assessment
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM Assessment WHERE AssessmentIdentifier = $1", id)
	return err
}
