// Code generated by go generate; DO NOT EDIT.
package educationorg

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type EducationOrg struct {
	Field0 *string `json:"organizationidentifier"`

	Field1 *string `json:"organizationname"`
}

func (r *Repository) List(limit, offset int) ([]EducationOrg, error) {
	rows, err := r.db.Query("SELECT OrganizationIdentifier, OrganizationName FROM edfi.School LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []EducationOrg
	for rows.Next() {
		var s EducationOrg
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*EducationOrg, error) {
	row := r.db.QueryRow("SELECT OrganizationIdentifier, OrganizationName FROM edfi.School WHERE OrganizationIdentifier = $1", id)
	var s EducationOrg
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM edfi.School WHERE OrganizationIdentifier = $1", id)
	return err
}
