// Code generated by go generate; DO NOT EDIT.
package credential

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

func (r *Repository) List(limit, offset int) ([]interface{}, error) {
	return []interface{}{}, nil
}
