//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type Domain struct {
	Name     string
	Table    string
	Cols     []string
	Struct   string
	Endpoint string
}

func (d Domain) HasTable() bool {
	return d.Table != ""
}

func (d Domain) ColsJoined() string {
	return strings.Join(d.Cols, ", ")
}

func (d Domain) IdCol() string {
	if len(d.Cols) > 0 {
		return d.Cols[0]
	}
	return ""
}

func main() {
	var repoTmpl = template.Must(template.New("repo").Funcs(template.FuncMap{
		"toLower": strings.ToLower,
	}).Parse(`// Code generated by go generate; DO NOT EDIT.
package {{.Name}}

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

{{if .HasTable}}
type {{.Struct}} struct {
{{range $i, $col := .Cols}}
	Field{{$i}} *string ` + "`" + `json:"{{$col | toLower}}"` + "`" + `
{{end}}
}

func (r *Repository) List(limit, offset int) ([]{{.Struct}}, error) {
	rows, err := r.db.Query("SELECT {{.ColsJoined}} FROM {{.Table}} LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []{{.Struct}}
	for rows.Next() {
		var s {{.Struct}}
		if err := rows.Scan({{range $i, $col := .Cols}}{{if $i}}, {{end}}&s.Field{{$i}}{{end}}); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*{{.Struct}}, error) {
	row := r.db.QueryRow("SELECT {{.ColsJoined}} FROM {{.Table}} WHERE {{.IdCol}} = $1", id)
	var s {{.Struct}}
	if err := row.Scan({{range $i, $col := .Cols}}{{if $i}}, {{end}}&s.Field{{$i}}{{end}}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM {{.Table}} WHERE {{.IdCol}} = $1", id)
	return err
}
{{else}}
func (r *Repository) List(limit, offset int) ([]interface{}, error) {
	return []interface{}{}, nil
}
{{end}}
`))

	var handlerTmpl = template.Must(template.New("handler").Parse(`// Code generated by go generate; DO NOT EDIT.
package {{.Name}}

import (
	"encoding/json"
	"net/http"
	"os"
)

type Handler struct {
	repo *Repository
}

func NewHandler(repo *Repository) *Handler {
	return &Handler{repo: repo}
}

func (h *Handler) Register(mux *http.ServeMux) {
	prefix := os.Getenv("OASIS_PLUGIN_PREFIX")
	if prefix == "" {
		prefix = "api/common"
	}
	basePath := "/" + prefix + "/ed-fi/{{.Endpoint}}"
	mux.HandleFunc("GET "+basePath, h.list)
	mux.HandleFunc("GET "+basePath+"/{id}", h.{{if .HasTable}}get{{else}}notImplemented{{end}})
	mux.HandleFunc("POST "+basePath, h.{{if .HasTable}}create{{else}}notImplemented{{end}})
	mux.HandleFunc("PUT "+basePath+"/{id}", h.{{if .HasTable}}update{{else}}notImplemented{{end}})
	mux.HandleFunc("DELETE "+basePath+"/{id}", h.{{if .HasTable}}delete{{else}}notImplemented{{end}})
}

func (h *Handler) list(w http.ResponseWriter, r *http.Request) {
	limit := 50
	offset := 0
	items, err := h.repo.List(limit, offset)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	if items == nil {
		items = make([]{{if .HasTable}}{{.Struct}}{{else}}interface{}{{end}}, 0)
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(items)
}

{{if .HasTable}}
func (h *Handler) get(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	item, err := h.repo.Get(id)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	if item == nil {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(item)
}

func (h *Handler) create(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]string{"message": "created"})
}

func (h *Handler) update(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"message": "updated"})
}

func (h *Handler) delete(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	err := h.repo.Delete(id)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
{{else}}
func (h *Handler) notImplemented(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}
{{end}}
`))

	domains := []Domain{
		{Name: "academicrecord", Endpoint: "student-academic-records"},
		{Name: "assessment", Table: "Assessment", Cols: []string{"AssessmentIdentifier", "AssessmentTitle"}, Struct: "Assessment", Endpoint: "assessments"},
		{Name: "attendance", Table: "CourseSectionAttendance", Cols: []string{"CourseSectionIdentifier", "AttendanceEventType"}, Struct: "Attendance", Endpoint: "attendances"},
		{Name: "bellschedule", Endpoint: "bell-schedules"},
		{Name: "calendar", Table: "Calendar", Cols: []string{"CalendarCode", "CalendarDescription", "SchoolYear"}, Struct: "Calendar", Endpoint: "calendars"},
		{Name: "cohort", Endpoint: "cohorts"},
		{Name: "coursecatalog", Table: "CTECourse", Cols: []string{"CourseIdentifier", "CourseTitle"}, Struct: "Course", Endpoint: "course-catalogs"},
		{Name: "credential", Endpoint: "credentials"},
		{Name: "discipline", Endpoint: "disciplines"},
		{Name: "educationorg", Table: "K12School", Cols: []string{"OrganizationIdentifier", "OrganizationName"}, Struct: "EducationOrg", Endpoint: "education-organizations"},
		{Name: "grades", Endpoint: "grades"},
		{Name: "graduation", Endpoint: "graduation-plans"},
		{Name: "intervention", Endpoint: "interventions"},
		{Name: "postsecondary", Endpoint: "post-secondary-events"},
		{Name: "program", Table: "Program", Cols: []string{"ProgramName", "ProgramType"}, Struct: "Program", Endpoint: "programs"},
		{Name: "section", Table: "CourseSection", Cols: []string{"CourseSectionIdentifier", "CourseTitle"}, Struct: "Section", Endpoint: "sections"},
		{Name: "staff", Table: "K12Staff", Cols: []string{"StaffIdentifier", "FirstName", "LastOrSurname"}, Struct: "Staff", Endpoint: "staffs"},
		{Name: "student", Table: "K12Student", Cols: []string{"StudentIdentifier", "FirstName", "LastOrSurname"}, Struct: "Student", Endpoint: "students"},
		{Name: "studentsection", Table: "CourseSectionEnrollment", Cols: []string{"CourseSectionIdentifier", "StudentIdentifier"}, Struct: "StudentSection", Endpoint: "student-section-associations"},
	}

	for _, d := range domains {
		dir := filepath.Join("internal", d.Name)
		if err := os.MkdirAll(dir, 0755); err != nil {
			log.Fatalf("failed to create directory %s: %v", dir, err)
		}

		// Generate repository.go
		var repoBuf bytes.Buffer
		if err := repoTmpl.Execute(&repoBuf, d); err != nil {
			log.Fatalf("failed to execute repo template for %s: %v", d.Name, err)
		}
		repoFmt, err := format.Source(repoBuf.Bytes())
		if err != nil {
			log.Fatalf("failed to format repo.go for %s: %v\n%s", d.Name, err, repoBuf.String())
		}
		if err := os.WriteFile(filepath.Join(dir, "repository.go"), repoFmt, 0644); err != nil {
			log.Fatalf("failed to write repo.go for %s: %v", d.Name, err)
		}

		// Generate handler.go
		var handlerBuf bytes.Buffer
		if err := handlerTmpl.Execute(&handlerBuf, d); err != nil {
			log.Fatalf("failed to execute handler template for %s: %v", d.Name, err)
		}
		handlerFmt, err := format.Source(handlerBuf.Bytes())
		if err != nil {
			log.Fatalf("failed to format handler.go for %s: %v\n%s", d.Name, err, handlerBuf.String())
		}
		if err := os.WriteFile(filepath.Join(dir, "handler.go"), handlerFmt, 0644); err != nil {
			log.Fatalf("failed to write handler.go for %s: %v", d.Name, err)
		}
		
		fmt.Printf("Generated %s\n", d.Name)
	}
}
