// Code generated by go generate; DO NOT EDIT.
package section

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Section struct {
	Field0 *string `json:"coursesectionidentifier"`

	Field1 *string `json:"coursetitle"`
}

func (r *Repository) List(limit, offset int) ([]Section, error) {
	rows, err := r.db.Query("SELECT CourseSectionIdentifier, CourseTitle FROM edfi.Section LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Section
	for rows.Next() {
		var s Section
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Section, error) {
	row := r.db.QueryRow("SELECT CourseSectionIdentifier, CourseTitle FROM edfi.Section WHERE CourseSectionIdentifier = $1", id)
	var s Section
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM edfi.Section WHERE CourseSectionIdentifier = $1", id)
	return err
}
