// Code generated by go generate; DO NOT EDIT.
package cohort

import (
	"encoding/json"
	"net/http"
	"os"
	"strconv"
)

type Handler struct {
	repo *Repository
}

func NewHandler(repo *Repository) *Handler {
	return &Handler{repo: repo}
}

func (h *Handler) Register(mux *http.ServeMux) {
	prefix := os.Getenv("OASIS_PLUGIN_PREFIX")
	if prefix == "" {
		prefix = "api/common"
	}
	basePath := "/" + prefix + "/ed-fi/cohorts"
	mux.HandleFunc("GET "+basePath, h.list)
	mux.HandleFunc("GET "+basePath+"/{id}", h.notImplemented)
	mux.HandleFunc("POST "+basePath, h.notImplemented)
	mux.HandleFunc("PUT "+basePath+"/{id}", h.notImplemented)
	mux.HandleFunc("DELETE "+basePath+"/{id}", h.notImplemented)
}

func (h *Handler) list(w http.ResponseWriter, r *http.Request) {
	limit := 50
	offset := 0
	if l := r.URL.Query().Get("limit"); l != "" {
		if parsed, err := strconv.Atoi(l); err == nil && parsed > 0 {
			limit = parsed
		}
	}
	if o := r.URL.Query().Get("offset"); o != "" {
		if parsed, err := strconv.Atoi(o); err == nil && parsed >= 0 {
			offset = parsed
		}
	}
	items, err := h.repo.List(limit, offset)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	if items == nil {
		items = make([]interface{}, 0)
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(items)
}

func (h *Handler) notImplemented(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}
