#!/usr/bin/env bash

go build -o ./plugins/common ./plugin/common
go build -o ./plugins/common-ui ./plugin/common-ui
go build -o ./plugins/admin ./plugin/admin
go build -o ./plugins/admin-ui ./plugin/admin-ui
