// Code generated by go generate; DO NOT EDIT.
package attendance

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Attendance struct {
	Field0 *string `json:"coursesectionidentifier"`

	Field1 *string `json:"attendanceeventtype"`
}

func (r *Repository) List(limit, offset int) ([]Attendance, error) {
	rows, err := r.db.Query("SELECT CourseSectionIdentifier, AttendanceEventType FROM edfi.StudentSectionAttendanceEvent LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Attendance
	for rows.Next() {
		var s Attendance
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Attendance, error) {
	row := r.db.QueryRow("SELECT CourseSectionIdentifier, AttendanceEventType FROM edfi.StudentSectionAttendanceEvent WHERE CourseSectionIdentifier = $1", id)
	var s Attendance
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM edfi.StudentSectionAttendanceEvent WHERE CourseSectionIdentifier = $1", id)
	return err
}
