// Code generated by go generate; DO NOT EDIT.
package academicrecord

import (
	"encoding/json"
	"net/http"
)

type Handler struct {
	repo *Repository
}

func NewHandler(repo *Repository) *Handler {
	return &Handler{repo: repo}
}

func (h *Handler) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /ed-fi/student-academic-records", h.list)
	mux.HandleFunc("GET /ed-fi/student-academic-records/{id}", h.notImplemented)
	mux.HandleFunc("POST /ed-fi/student-academic-records", h.notImplemented)
	mux.HandleFunc("PUT /ed-fi/student-academic-records/{id}", h.notImplemented)
	mux.HandleFunc("DELETE /ed-fi/student-academic-records/{id}", h.notImplemented)
}

func (h *Handler) list(w http.ResponseWriter, r *http.Request) {
	limit := 50
	offset := 0
	items, err := h.repo.List(limit, offset)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	if items == nil {
		items = make([]interface{}, 0)
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(items)
}

func (h *Handler) notImplemented(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}
