// Code generated by go generate; DO NOT EDIT.
package coursecatalog

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Course struct {
	Field0 *string `json:"courseidentifier"`

	Field1 *string `json:"coursetitle"`
}

func (r *Repository) List(limit, offset int) ([]Course, error) {
	rows, err := r.db.Query("SELECT CourseIdentifier, CourseTitle FROM edfi.Course LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Course
	for rows.Next() {
		var s Course
		if err := rows.Scan(&s.Field0, &s.Field1); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Course, error) {
	row := r.db.QueryRow("SELECT CourseIdentifier, CourseTitle FROM edfi.Course WHERE CourseIdentifier = $1", id)
	var s Course
	if err := row.Scan(&s.Field0, &s.Field1); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM edfi.Course WHERE CourseIdentifier = $1", id)
	return err
}
