// Code generated by go generate; DO NOT EDIT.
package staff

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Staff struct {
	Field0 *string `json:"staffidentifier"`

	Field1 *string `json:"firstname"`

	Field2 *string `json:"lastorsurname"`
}

func (r *Repository) List(limit, offset int) ([]Staff, error) {
	rows, err := r.db.Query("SELECT StaffIdentifier, FirstName, LastOrSurname FROM K12Staff LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Staff
	for rows.Next() {
		var s Staff
		if err := rows.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Staff, error) {
	row := r.db.QueryRow("SELECT StaffIdentifier, FirstName, LastOrSurname FROM K12Staff WHERE StaffIdentifier = $1", id)
	var s Staff
	if err := row.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM K12Staff WHERE StaffIdentifier = $1", id)
	return err
}
