// Code generated by go generate; DO NOT EDIT.
package student

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Student struct {
	Field0 *string `json:"studentuniqueid"`

	Field1 *string `json:"firstname"`

	Field2 *string `json:"lastsurname"`
}

func (r *Repository) List(limit, offset int) ([]Student, error) {
	rows, err := r.db.Query("SELECT StudentUniqueId, FirstName, LastSurname FROM edfi.Student LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Student
	for rows.Next() {
		var s Student
		if err := rows.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Student, error) {
	row := r.db.QueryRow("SELECT StudentUniqueId, FirstName, LastSurname FROM edfi.Student WHERE StudentUniqueId = $1", id)
	var s Student
	if err := row.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM edfi.Student WHERE StudentUniqueId = $1", id)
	return err
}
