// Code generated by go generate; DO NOT EDIT.
package calendar

import (
	"database/sql"
)

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

type Calendar struct {
	Field0 *string `json:"calendarcode"`

	Field1 *string `json:"calendardescription"`

	Field2 *string `json:"schoolyear"`
}

func (r *Repository) List(limit, offset int) ([]Calendar, error) {
	rows, err := r.db.Query("SELECT CalendarCode, CalendarDescription, SchoolYear FROM Calendar LIMIT $1 OFFSET $2", limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Calendar
	for rows.Next() {
		var s Calendar
		if err := rows.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, nil
}

func (r *Repository) Get(id string) (*Calendar, error) {
	row := r.db.QueryRow("SELECT CalendarCode, CalendarDescription, SchoolYear FROM Calendar WHERE CalendarCode = $1", id)
	var s Calendar
	if err := row.Scan(&s.Field0, &s.Field1, &s.Field2); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &s, nil
}

func (r *Repository) Delete(id string) error {
	_, err := r.db.Exec("DELETE FROM Calendar WHERE CalendarCode = $1", id)
	return err
}
